### ISSUE TITLE
Bug in server side

### ISSUE THREAD

**Issue by ShadiqurShaon** [ShadiqurShaon/profile#5]
From home page it is navigating to portfolio page but when "https://profile-c283e.firebaseapp.com/portfolio"
is refresh 404 is showing.  if anything to know please let me know

**Comment by ShadiqurShaon** [comment]
i think this is an webpack issue

**Comment by shadman-ahmed** [comment]
can you please share your firebase.json

**Comment by shadman-ahmed** [comment]
can you please share your `firebase.json`

**Comment by ShadiqurShaon** [comment]
Please check this out
[firebase.zip](https://github.com/ShadiqurShaon/profile/files/1986399/firebase.zip)

**Comment by shadman-ahmed** [comment]
please add rewrites to your firebase.json `{
  "hosting": {
    "public": "dist",
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}`
Documentation: [https://vuejs.org/v2/guide/routing.html#Official-Router](url)
